# This is a basic workflow to help you get started with Actions

name: Push to Knowledge Based

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      # - name: creates output
      #   run:  sh ./build.sh
      - name: Pushes to another repository
        uses: rochmadnurdin/System@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          destination-github-username: 'rochmadnurdin'
          destination-repository-name: 'knowledgebase'
          user-email: dev@alterra.id
          destination-branch: master
          system-name: 'BPA/Civet'

